parser: DefaultV1

steps:
  - id: step1
    name: create file
    verifyScript: scripts/verify-file-exists.sh
    execScript: scripts/create-file.sh

  - id: step2
    name: file has content
    verifyScript: scripts/verify-has-content.sh
    execScript: scripts/write-content.sh

flow:
  - id: step1
  - id: step2